```{r}
#All libraries that have to be downloaded to work 

library(readr)
library(dplyr)
library(ggplot2)
library(sf)
library(terra)
library(tmap)
```

```{r}
#Import and explore data
jojo <- read_delim("20220504_sanglier_SFN.csv", 
    delim = ";", escape_double = FALSE, col_types = cols(OID_ = col_number(), 
        NO = col_number(), CollarID = col_number(), 
        Date = col_date(format = "%d.%m.%Y"), 
        Time = col_time(format = "%H:%M:%S"), 
        Latitude = col_number(), Longitude = col_number(), 
        Altitude = col_number(), TEMP = col_number(), 
        ORIG_OID = col_number(), X = col_number(), 
        Y = col_number()), trim_ws = TRUE)
View(jojo)

#Jojo was captured the 03.09.2019 and disappeared the 26.07.2021
#1 data per hour from 17h to 05h, then 1x at 11h 
#X and Y-coord are available as the height
```

```{r}
#visualizing the data with a plot 
PLOT1 <- ggplot(jojo, aes(X, Y)) + geom_point(aes(color = "orange"), show.legend = FALSE) 
PLOT1
```

```{r}
#Project Data on a map 
jojo_sf <- st_as_sf(jojo, coords = c("X", "Y"), crs = 2056)
jojo_grouped <- group_by(jojo_sf,CollarID)
jojo_smry <- summarise(jojo_grouped)
jojo_mcp <- st_convex_hull(jojo_smry)
plot(jojo_mcp)
```

```{r}
#Getting a map of the region 
#the map was downloaded from swisstopo and cropped on ArcGisPro to get a regional map
regio_map <- terra::rast("regio_map.tif")
plot(regio_map)
```

```{r}
tm_shape(regio_map) + tm_rgb() + tm_shape(jojo_mcp) + tm_polygons(col = "orange",alpha = 0.3,border.col = "red") + tm_layout(main.title = "Global distribution map")
```

```{r}

```

